% -------------------------------------------------------------------
%  Generated by MATLAB on 19-Sep-2026 10:51:55
%  MATLAB version: 26.1.0.3312084 (R2026a) Update 4
% -------------------------------------------------------------------
                                           

Sig = Simulink.Signal;
Sig.CoderInfo.StorageClass = 'Auto';
Sig.Description = '';
Sig.DataType = 'auto';
Sig.Min = [];
Sig.Max = [];
Sig.DocUnits = '';
Sig.Dimensions = -1;
Sig.DimensionsMode = 'auto';
Sig.Complexity = 'auto';
Sig.SampleTime = -1;
Sig.InitialValue = '';

